services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-jenkins-docker-ci-app}:${IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped



